spring.application.name=AlphaTransport-VehicleTracking
server.port=9192
# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/alphatransport

# Database username
spring.datasource.username=root

# Database password
spring.datasource.password=Gaya@9934023936

# Database driver class name
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# JPA properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jackson.serialization.write-dates-as-timestamps=false
